'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class eir_container
    Public Property eir As String
    Public Property contenedor As String
    Public Property sello As String
    Public Property responsable As Nullable(Of Integer)
    Public Property empresa As Nullable(Of Integer)

    Public Overridable Property empresa1 As empresa
    Public Overridable Property responsable1 As responsable

End Class
