'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empresa
    Public Property empresa1 As Integer
    Public Property empresa_nombre As String

    Public Overridable Property eir_container As ICollection(Of eir_container) = New HashSet(Of eir_container)

End Class
